### PR TITLE
Raise CodecException when error occured in decoder/encoder

### LINKED ISSUE #228: LwM2mNodeEncoder should raise a checked exception if the node is invalid
As an example, if the node cannot be encoded because of an incompatibility between the node and the model (e.g. invalid value type), a runtime `IllegalArgumentException` is raised. 
It would be cleaner to have a checked exception with a proper message so that the caller is able to handle this specific failure.

### PR DESCRIPTION
**Pull request by sbernard31**
This PR aims to fix #228.

### CODE REVIEW

File: leshan-core/src/main/java/org/eclipse/leshan/core/node/codec/Lwm2mNodeEncoderUtil.java [hunk 1]
```diff
@@ -141,12 +142,16 @@ public static Object convertValue(Object value, Type currentType, Type expectedT
                 // let's assume we received an hexadecimal string
                 LOG.debug("Trying to convert hexadecimal string {} to byte array", value);
                 // TODO: check if we shouldn't instead assume that the string contains Base64 encoded data
-                return Hex.decodeHex(((String) value).toCharArray());
+                try {
+                    return Hex.decodeHex(((String) value).toCharArray());
+                } catch (IllegalArgumentException e) {
+                    throw new CodecException(String.format("Unalble to convert hexastring [%s] to byte array", value));
```
Comment (msangoi) [inline leshan-core/src/main/java/org/eclipse/leshan/core/node/codec/Lwm2mNodeEncoderUtil.java]: typo

File: leshan-client-cf/src/main/java/org/eclipse/leshan/client/californium/impl/ObjectResource.java [hunk 2]
```diff
@@ -216,7 +216,7 @@ public void handlePUT(final CoapExchange coapExchange) {
                 }
 
                 return;
-            } catch (InvalidValueException e) {
+            } catch (CodecException e) {
                 LOG.warn("Unable to decode payload to write", e);
                 coapExchange.respond(ResponseCode.INTERNAL_SERVER_ERROR);
```
Comment (msangoi) [inline leshan-client-cf/src/main/java/org/eclipse/leshan/client/californium/impl/ObjectResource.java]: BAD_REQUEST?

File: leshan-core/src/main/java/org/eclipse/leshan/core/node/codec/tlv/LwM2mNodeTlvEncoder.java [hunk 3]
```diff
@@ -185,7 +186,7 @@ private Tlv encodeResource(LwM2mResource resource) {
             case OBJLNK:
                 return TlvEncoder.encodeObjlnk((ObjectLink) value);
```
Comment (msangoi) [inline leshan-core/src/main/java/org/eclipse/leshan/core/node/codec/tlv/LwM2mNodeTlvEncoder.java]: A try/catch block (for IllegalArgumentException) should be added here around all TlvEncoder.encode() methods. 
And it may be cleaner to raise TlvException instead of IllegalArgumentException in the TlvEncoder class.
